<?php // $Id: mimemail_compress.module,v 1.3 2009/02/23 04:28:46 jerdavis Exp $

/**
 * @file
 * Component module for sending Mime-encoded emails.
 */

/**
 * Mimemail postprocess
 */
function mimemail_compress_mail_post_process(&$message, $mailkey) {
  module_load_include('inc', 'mimemail_compress');
  // Separate CSS from HTML for processing
  $parts = mimemail_compress_clean_message($message);
  // Compress HTML and CSS into combined message
  $output = new mimemail_compress($parts['html'], $parts['css']);
  $output = $output->compress();
  $message = $output;
}
